### ISSUE TITLE
500 error when change page size

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-earnings-api#111]
https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-06-18%20at%209.13.22%20AM.mp4?

**Comment by Kpoke** [comment]
This has been resolved by https://github.com/Greenstand/treetracker-stakeholder-api/pull/28

**Comment by Kpoke** [comment]
Thought that fixed it but it didn't

**Comment by Kpoke** [comment]
This has been fixed by reducing the max pool in the stakeholders API https://github.com/Greenstand/treetracker-stakeholder-api/pull/29
