### ISSUE TITLE
implement organization filter

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-earnings-api#24]
Funder filter
Planting organization filter
We need to show both funder and planting organization on the earnings & payments (and CSV?)

**Comment by dadiorchen** [comment]
For now, we can ignore the `filter by org`, just do it on `funder`.

**Comment by Mloweedgar** [comment]
Okay @dadiorchen, I will do that.

**Comment by dadiorchen** [comment]
@Mloweedgar I have opened issues about filtering by sub org, that would be the exact description for this job.

**Comment by dadiorchen** [comment]
https://github.com/Greenstand/treetracker-admin-client/issues/476
