### ISSUE TITLE
The error message could be more clear when uploaded wrong format of CSV

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-earnings-api#26]
[https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-03-03%20at%2010.32.43%20AM.mp4](url)

Maybe we need to do an entire check for the CSV file, to make sure: 
* The CVS format should be fine
* The fields should match our requirement, 
* Maybe check the value type of every column

**Comment by ZavenArra** [comment]
definitely agree

**Comment by dadiorchen** [comment]
This is fine, the error is about excpeiton in s3 settings, it's normally impossible for end-user.
