### ISSUE TITLE
Display capture account in the cvs file

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-earnings-api#27]
I think it is better we put the `capture_count` into the exported csv file.

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-03-03%20at%2010.30.31%20AM.mp4

**Comment by ZavenArra** [comment]
yes

**Comment by dadiorchen** [comment]
This is just about save the capture_count into the exporting CVS file.
