### ISSUE TITLE
CORS policy?

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-earnings-api#54]

**Comment by dadiorchen** [comment]
Now I opened the whole CORS policy

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/5744708/158735161-de683bde-270d-4a8b-b094-68310e5277ad.png">

**Comment by ZavenArra** [comment]
Can you show me where you opened CORS?

It's supposed to happen via mapping.yaml in the deployment, not in code, and it needs to be specific for each environment.  Check on the treetracker-messaging-api to see the correct way to open CORS for an API in use by the admin panel.

**Comment by dadiorchen** [comment]
I have to set it here:

https://github.com/Greenstand/treetracker-messaging-api/blob/d92d05386ca2719176c70002206ceb58792a4f0f/server/app.js#L12-L14

I noticed that the dev is open for everyone, https://github.com/Greenstand/treetracker-messaging-api/blob/main/deployment/overlays/development/mapping.yaml

And test is close on this: https://github.com/Greenstand/treetracker-messaging-api/blob/main/deployment/overlays/test/mapping.yaml
