### ISSUE TITLE
Can upload bad file as payment

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-earnings-api#75]
[up-badFields.csv](https://github.com/Greenstand/treetracker-earnings-api/files/8423172/up-badFields.csv)
[up-badValues.csv](https://github.com/Greenstand/treetracker-earnings-api/files/8423173/up-badValues.csv)

**Comment by philnorc** [comment]
In tests just now (April 6, 16:30 Chicago time)
the tool properly rejected upload files with missing fields or empty values.
It also rejected files with good data values, but without field names in line 1.

**Comment by philnorc** [comment]
Yes, right, the line 1 of the file must be "earnings_id","worker_id","phone","currency","amount","captures_count","payment_confirmation_id","payment_method","paid_at"
