### ISSUE TITLE
Batch uploads return false positives 

### ISSUE THREAD

**Issue by philnorc** [Greenstand/treetracker-earnings-api#86]
Export some paid records.
1 Upload one of those records with no changes.
2 Upload one of those records with a new record ID
3 Upload one of those records with a new phone number

In all three cases the return message is "Payment Uploaded Successfully"
They should return errors:
1 No new values uploaded for a record
2 You cannot use this tool to create new records or record IDs
3. You cannot change existing values in a record. You can only replace empty values.

**Comment by dadiorchen** [comment]
Confirmed all these problem, I will close this one and open three new one for them respectively.
